# Site settings
title: rsy's blog
email: netheril96@gmail.com
baseurl: "/blogs" # the subpath of your site, e.g. /blog/
url: "https://netheril96.github.io" # the base hostname & protocol for your site
github_username: netheril96

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge
kramdown:
        input: GFM
